### PR TITLE
GitHub actions templates

### PR DESCRIPTION
**Pull request by hupling**
**Description**

In this PR three Workflows were created.

`Compliance check and build test`: This action has two jobs:
1. Compliance check with Policy as Code
2. Maven buiild with tests

`Build and publish an image`: This action performs a Maven build and pushen afterwards an image (`package`) to the GitHub Registry of the repository.

`Build GitHub release and bump SNAPSHOT`: This action has two jobs:
1. Setting the Maven version to the next non-SNAPSHOT one and creating a GitHub Tag and Release afterwerds with the new version. E.g. `0.0.2-SNAPSHOT` into `0.0.2` with Release and tag `0.0.2`
2. Increasing the project Maven version to the next SNAPSHOT version. E.g. `0.2.5` into `0.2.6-SNAPSHOT`

**Reference**

Issues https://git.muenchen.de/ccse/ospo/-/issues/264
Comment: https://git.muenchen.de/ccse/ospo/-/issues/264#note_732239

### CODE REVIEW

**Comment by FabianWilms** [comment]
I think this would be better suited to only be included in https://github.com/it-at-m/oss-repository-en-template/tree/main/.github/workflows as it's the main template repository.

The `.github`-Repository of this organization is just a fallback if a repo in this org doesn't have a `.github`-Folder. So currently it's purpose is to add a LICENCE-File and a PR-Template to empty repositories.

Adding this pipeline to each repository that doesn't have a build.yaml, publish.yaml etc. seems very counterintuitive.

**Comment by hupling** [comment]
> I think this would be better suited to only be included in https://github.com/it-at-m/oss-repository-en-template/tree/main/.github/workflows as it's the main template repository.
> 
> The `.github`-Repository of this organization is just a fallback if a repo in this org doesn't have a `.github`-Folder. So currently it's purpose is to add a LICENCE-File and a PR-Template to empty repositories.
> 
> Adding this pipeline to each repository that doesn't have a build.yaml, publish.yaml etc. seems very counterintuitive.

Someone said, that not every repo is a java or nodejs repo.  https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization

**Comment by FabianWilms** [comment]
Sorry, i didn't know about

> They offer an alternative to starting from a blank workflow file and are useful because some of the work will already have been done for you.

I thought the workflows in this repo would automatically be active in new repositories. In this case I also think it's a great idea!

**Comment by hupling** [comment]
@ejcsid @banzuu ich habe den MR https://github.com/it-at-m/oss-repository-en-template/pull/21 von @mirrodi weitergeführt, aber das ist jetzt nur ein erster Entwurf. Es muss noch weiter Arbeit hineingesteckt werden. Ich kann euch leider nicht als Reviewer eintragen.

**Review by ejcsid — APPROVED** [review]
@hupling  Seems ok. Do we have an example to check these workflows?

**Comment by hupling** [comment]
> @hupling Seems ok. Do we have an example to check these workflows?

grafik

Alle Templates wurden in den Testprojekten hinzugefügt.

- https://github.com/it-at-m/sps-frontend
- https://github.com/it-at-m/sps-backend

**Pull request merged**
